### ISSUE TITLE
关于mcdr 2.0

### ISSUE THREAD

**Issue by 401U** [A-JiuA/Online#2]
mcdr 2.0现在已经发布, 新的插件仓库是基于github release 自动构建的, 我已经在https://github.com/FAS-Server/Online 仓库下做好了相关改动, 所以想咨询一下插件该怎么发布, 是
 1. pr到你这边然后你在插件仓库提交
 2. 直接以FAS-Server的仓库进行提交
 鉴于2.0的插件仓库有对插件id作出不能重复的要求, 这个关系到后续的插件发布更新, 所以打扰了

**Comment by Lyxot** [comment]
直接以FAS-Server的仓库进行提交吧
