### ISSUE TITLE
配置之后不起作用，控制台报错

### ISSUE THREAD

**Issue by goolured** [A-JiuA/Online#3]
[MCDR] [15:08:00] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=online@1.1.0,priority=1000,callback=<function on_info at 0x000002D9909C55A0>]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\BedDi\[25565]survival\mcdreforged\plugin\plugin_manager.py", line 474, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "C:\Users\Administrator\Desktop\BedDi\[25565]survival\mcdreforged\plugin\plugin_event.py", line 79, in execute
    return self.callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\BedDi\[25565]survival\plugins\online.py", line 168, in on_info
    server.say(get_list())
  File "C:\Users\Administrator\Desktop\BedDi\[25565]survival\plugins\online.py", line 131, in get_list
    config = get_config()
  File "C:\Users\Administrator\Desktop\BedDi\[25565]survival\plugins\online.py", line 108, in get_config
    config = json.load(f, encoding='UTF-8')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

**Comment by goolured** [comment]
插件可以正常加载，但是输入指令就报错

**Comment by Lyxot** [comment]
本插件已经长时间未维护,请访问[这个链接](https://github.com/MCDReforged/PluginCatalogue/blob/catalogue/plugins/online/readme-zh_cn.md)使用由[FAS-Server](https://github.com/FAS-Server)维护的插件

**Comment by goolured** [comment]
那玩意要multirconAPI，https://github.com/FAS-Server/MultiRconAPI/issues/1😭

> 本插件已经长时间未维护,请访问[这个链接](https://github.com/MCDReforged/PluginCatalogue/blob/catalogue/plugins/online/readme-zh_cn.md)使用由[FAS-Server](https://github.com/FAS-Server)维护的插件

**Comment by Lyxot** [comment]
你的配置文件是否以UTF-8编码保存?如果不是,请以UTF-8编码保存

**Comment by HeyRed233** [comment]
> 你的配置文件是否以UTF-8编码保存?如果不是,请以UTF-8编码保存

![Uploading 屏幕截图 2022-02-01 160459.png…]()

**Comment by goolured** [comment]
> 你的配置文件是否以UTF-8编码保存?如果不是,请以UTF-8编码保存

刚刚发现了我的mcdr不是最新版本，然后我更新了之后它的错误变成了这个
![屏幕截图 2022-02-01 164125](https://user-images.githubusercontent.com/64000498/151937201-86fe452f-4313-4a44-b614-5bfc2ea3082a.png)

**Comment by goolured** [comment]
> 你的配置文件是否以UTF-8编码保存?如果不是,请以UTF-8编码保存

尝试过了，还是不行，同样的显示没有响应

**Comment by goolured** [comment]
刚刚从https://github.com/FAS-Server/MultiRconAPI/issues/1 获得了帮助，插件能够正常加载
但目前是输入online
![屏幕截图 2022-02-01 232829](https://user-images.githubusercontent.com/64000498/151998177-5b88d5b3-05b1-4965-bdec-4bf2b05a43e4.png)
没有任何的反应

**Comment by Lyxot** [comment]
> 刚刚从https://github.com/FAS-Server/MultiRconAPI/issues/1 获得了帮助，插件能够正常加载
> 但目前是输入online
> ![屏幕截图 2022-02-01 232829](https://user-images.githubusercontent.com/64000498/151998177-5b88d5b3-05b1-4965-bdec-4bf2b05a43e4.png)
> 没有任何的反应

从游戏中输入!!online试试

**Comment by goolured** [comment]
> > 刚刚从[FAS-Server/MultiRconAPI#1](https://github.com/FAS-Server/MultiRconAPI/issues/1) 获得了帮助，插件能够正常加载
> > 但目前是输入online
> > ![屏幕截图 2022-02-01 232829](https://user-images.githubusercontent.com/64000498/151998177-5b88d5b3-05b1-4965-bdec-4bf2b05a43e4.png)
> > 没有任何的反应
> 
> 从游戏中输入!!online试试
一样没有反应
![屏幕截图 2022-02-01 233624](https://user-images.githubusercontent.com/64000498/151999404-93a061bd-a628-40ba-a58d-c8f5d4ea6394.png)

**Comment by goolured** [comment]
!!online
[MCDR] [11:28:36] [ConsoleHandler/DEBUG]: Parsed text from ConsoleHandler:
[MCDR] [11:28:36] [ConsoleHandler/DEBUG]: Time: 11:28:36; ID: 3629
[MCDR] [11:28:36] [ConsoleHandler/DEBUG]: Player: None; Source: 1; Logging level: None
[MCDR] [11:28:36] [ConsoleHandler/DEBUG]: Content: !!online
[MCDR] [11:28:36] [ConsoleHandler/DEBUG]: Raw content: !!online
[MCDR] [11:28:36] [TaskExecutor/DEBUG]: Dispatching MCDREvent[name=General info] with args (Info)
[MCDR] [11:28:36] [TaskExecutor/DEBUG]: Dispatching MCDREvent[name=User info] with args (Info)

**Comment by goolured** [comment]
问题已解决，端口配置错误了
感谢给我提供了帮助

**Comment by Lyxot** [comment]
没有关系，问题我已了解

**Comment by Lyxot** [comment]
理论上我这版的插件可以应对端口填写错误的情况，并提示服务器未开启，也许是因为你填的端口是游戏端口才会出现这样的报错
