### ISSUE TITLE
[Bug]: 每次使用!!online指令时会先跳出一条client_to_query_online unset的info

### ISSUE THREAD

**Issue by ENDlezZenith** [A-JiuA/Online#4]
![image](https://github.com/user-attachments/assets/862171b1-d17e-4384-a3ad-51a5a8740849)
不管是在终端还是游戏内都会跳出
请问这是哪里没有配置导致的问题吗

**Comment by Lyxot** [comment]
这个插件已经长时间没有维护了，我也不了解问题原因

**Comment by ENDlezZenith** [comment]
好吧我再排查一下 有结果了过来更新

**Comment by ENDlezZenith** [comment]
看了下这是ChatBridge的选项 估计也是ChatBridge那里给的Info 那就和这里无关了
